#  Run this image on Windows, Linux or Mac (Intel)
services:
  selenium-hub:
    image: selenium/hub:4.33.0
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4443:4443"
      - "4442:4442"
    environment:
      - SE_ENABLE_TRACING=true
    healthcheck:
      test: "/opt/bin/check-grid.sh --host 0.0.0.0 --port 4444"
      interval: "15s"
      timeout: "30s"
      retries: 5
    restart: always

  chrome:
    image: selenium/node-chrome:4.33.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_NODE_GRID_URL=http://localhost:4444
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_VNC_NO_PASSWORD=1
      - SE_NODE_MAX_SESSIONS=5
      - SE_NODE_MAX_INSTANCES=5
      - SE_OPTS=--enable-managed-downloads true
      - SE_ENABLE_TRACING=false
      - JAVA_OPTS=-Djava.net.preferIPv4Stack=true
    restart: always
    deploy:
      mode: replicated
      replicas: 1
